### ISSUE TITLE
Mac M1 - Problem with Boost Lib

### ISSUE THREAD

**Issue by SeeTheInvisible** [dynexcoin/Dynex#6]
Anyone has a quick solution for the error:
Library not loaded: '/usr/local/homebrew/opt/boost/lib/libboost_program_options.dylib'
when executing dynexd on a MBPro M1.

Note: brew and the referenced boost libs are installed and are up to date.

**Comment by dynexcoin** [comment]
Yes, we have a solution. The reason is that Apple M1 compiles the boost libraries for ARM, whereas the precompiled MacOS version provided is based on the x86-64 architecture, which you cannot mix together. Here's how you solve it:

1) Download our pre-compiled boost runtime libraries for x86-64:
https://github.com/dynexcoin/Dynex/raw/main/libboost_x86-64.zip

2) Extract them into a folder

3) in the command line, you need to tell your environment where these boost (dynamic) libraries are located:
```
export DYLD_LIBRARY_PATH=/path/to/the/library/files/:$DYLD_LIBRARY_PATH
```

After that, you should be able to start the applications. Let us know if you need anything else!

**Comment by SeeTheInvisible** [comment]
Thanks for your quick reply - the prebuilt library files solved the problem!

Just a notice: Another issue was that the execution had been prevented by Mac OS's security settings. Having the "System Settings -> Security & Privacy -> General" page open while lauching the binary helps as the application then will be shown there besides an "Allow" button.
